# Generated by Django 5.0.1 on 2024-01-28 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='priemrApellido',
            new_name='primerApellido',
        ),
    ]
